use std::{
    fs,
    path::{Path, PathBuf},
};

use draft_model::{
    CommandEnvelope, CommandError, CommandErrorKind, CommandEvent, CommandName, CommandPayload,
    CommandResultEnvelope,
};
use schemars::schema_for;
use ts_rs::{Config, TS};

fn project_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .ancestors()
        .nth(2)
        .expect("draft_model should live under crates/")
        .to_path_buf()
}

#[test]
fn schema_exports_generated_contract_artifacts_from_rust() {
    let root = project_root();
    let schema_path = root.join("schemas/command.schema.json");
    let generated_dir = root.join("apps/desktop-electron/src/generated");

    fs::create_dir_all(schema_path.parent().expect("schema path should have parent"))
        .expect("schema directory should be created");
    fs::create_dir_all(&generated_dir).expect("generated TypeScript directory should be created");

    let schema = schema_for!(CommandEnvelope);
    let schema_json =
        serde_json::to_string_pretty(&schema).expect("command schema should serialize");
    fs::write(&schema_path, format!("{schema_json}\n")).expect("command schema should be written");

    write_ts(
        generated_dir.join("CommandEnvelope.ts"),
        &[
            export_decl::<CommandName>(),
            export_decl::<CommandPayload>(),
            export_decl::<CommandEnvelope>(),
        ],
    );
    write_ts(
        generated_dir.join("CommandResultEnvelope.ts"),
        &[
            export_decl::<CommandErrorKind>(),
            export_decl::<CommandError>(),
            export_decl::<CommandEvent>(),
            export_decl::<CommandResultEnvelope<()>>(),
        ],
    );
}

fn export_decl<T>() -> String
where
    T: TS + 'static,
{
    format!("export {}\n", T::decl(&Config::new()))
}

fn write_ts(path: PathBuf, declarations: &[String]) {
    let mut ts = String::from(
        "// This file was generated by Rust ts-rs declarations. Do not edit this file manually.\n\n",
    );
    for declaration in declarations {
        ts.push_str(declaration);
    }
    fs::write(path, ts).expect("TypeScript contract should be written");
}
