use std::{
    collections::BTreeSet,
    fs,
    path::{Path, PathBuf},
};

use draft_model::{
    CommandEnvelope, CommandError, CommandErrorKind, CommandEvent, CommandName, CommandPayload,
    CommandResultEnvelope, PingCommandPayload, ProbeMediaRuntimeCommandPayload,
    VersionCommandPayload,
};
use schemars::schema_for;
use ts_rs::{Config, TS};

fn project_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .ancestors()
        .nth(2)
        .expect("draft_model should live under crates/")
        .to_path_buf()
}

#[test]
fn schema_exports_generated_contract_artifacts_from_rust() {
    let root = project_root();
    let schema_path = root.join("schemas/command.schema.json");
    let generated_dir = root.join("apps/desktop-electron/src/generated");

    fs::create_dir_all(
        schema_path
            .parent()
            .expect("schema path should have parent"),
    )
    .expect("schema directory should be created");
    fs::create_dir_all(&generated_dir).expect("generated TypeScript directory should be created");

    let schema_json = command_schema_json();
    fs::write(&schema_path, format!("{schema_json}\n")).expect("command schema should be written");

    write_ts(
        generated_dir.join("CommandEnvelope.ts"),
        &[
            export_decl::<CommandName>(),
            export_decl::<PingCommandPayload>(),
            export_decl::<VersionCommandPayload>(),
            export_decl::<ProbeMediaRuntimeCommandPayload>(),
            export_decl::<CommandPayload>(),
            export_decl::<CommandEnvelope>(),
        ],
    );
    write_ts(
        generated_dir.join("CommandResultEnvelope.ts"),
        &[
            export_decl::<CommandErrorKind>(),
            export_decl::<CommandError>(),
            export_decl::<CommandEvent>(),
            export_decl::<CommandResultEnvelope<()>>(),
        ],
    );
}

fn export_decl<T>() -> String
where
    T: TS + 'static,
{
    format!("export {}\n", T::decl(&Config::new()))
}

fn write_ts(path: PathBuf, declarations: &[String]) {
    let mut ts = String::from(
        "// This file was generated by Rust ts-rs declarations. Do not edit this file manually.\n\n",
    );
    for declaration in declarations {
        ts.push_str(declaration);
    }
    fs::write(path, ts).expect("TypeScript contract should be written");
}

#[test]
fn schema_fixtures_validate_command_contracts() {
    let root = project_root();
    let fixture_dir = root.join("fixtures/draft");
    let positive = BTreeSet::from(["minimal-command.json"]);
    let negative = BTreeSet::from(["invalid-unknown-field.json"]);

    let fixture_names = fs::read_dir(&fixture_dir)
        .expect("fixtures/draft directory should exist")
        .map(|entry| {
            let entry = entry.expect("fixture directory entry should be readable");
            let path = entry.path();
            assert_eq!(
                path.extension().and_then(|extension| extension.to_str()),
                Some("json"),
                "fixtures/draft should only contain JSON fixtures: {}",
                path.display()
            );
            entry
                .file_name()
                .into_string()
                .expect("fixture names should be UTF-8")
        })
        .collect::<BTreeSet<_>>();

    let expected = positive.union(&negative).copied().collect::<BTreeSet<_>>();
    let actual = fixture_names
        .iter()
        .map(String::as_str)
        .collect::<BTreeSet<_>>();
    assert_eq!(
        actual, expected,
        "every draft JSON fixture must be explicitly classified"
    );

    let schema_json: serde_json::Value = serde_json::from_str(&command_schema_json())
        .expect("generated command schema should parse");
    let schema =
        jsonschema::validator_for(&schema_json).expect("generated command schema should compile");

    for fixture_name in positive {
        let value = read_fixture(&fixture_dir, fixture_name);
        serde_json::from_value::<CommandEnvelope>(value.clone())
            .expect("positive fixture should deserialize through Rust model");
        schema
            .validate(&value)
            .expect("positive fixture should validate against JSON Schema");
    }

    for fixture_name in negative {
        let value = read_fixture(&fixture_dir, fixture_name);
        assert!(
            serde_json::from_value::<CommandEnvelope>(value.clone()).is_err(),
            "negative fixture should fail Rust model deserialization: {fixture_name}"
        );
        assert!(
            schema.validate(&value).is_err(),
            "negative fixture should fail JSON Schema validation: {fixture_name}"
        );
    }
}

fn read_fixture(fixture_dir: &Path, fixture_name: &str) -> serde_json::Value {
    serde_json::from_slice(
        &fs::read(fixture_dir.join(fixture_name)).expect("fixture should be readable"),
    )
    .expect("fixture should parse as JSON")
}

fn command_schema_json() -> String {
    let schema = schema_for!(CommandEnvelope);
    serde_json::to_string_pretty(&schema).expect("command schema should serialize")
}
