use std::{
    collections::BTreeSet,
    env, fs,
    path::{Path, PathBuf},
};

use draft_model::{
    CommandEnvelope, CommandError, CommandErrorKind, CommandEvent, CommandName, CommandPayload,
    CommandResultEnvelope, Draft, DraftId, DraftMetadata, DraftSchemaVersion, Filter,
    ImportMaterialCommandPayload, ImportMaterialResponse, Keyframe, ListMaterialsCommandPayload,
    ListMaterialsResponse, ListMissingMaterialsCommandPayload, ListMissingMaterialsResponse,
    MainTrackMagnet, Material, MaterialId, MaterialKind, MaterialMetadata, MaterialStatus,
    Microseconds, MissingMaterialCommandDiagnostic, MissingMaterialCommandDiagnosticKind,
    PingCommandPayload, ProbeMediaRuntimeCommandPayload, RationalFrameRate, Segment, SegmentId,
    SourceTimerange, TargetTimerange, Track, TrackId, TrackKind, Transition, VersionCommandPayload,
};
use schemars::schema_for;
use serde_json::json;
use ts_rs::{Config, TS};

fn project_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .ancestors()
        .nth(2)
        .expect("draft_model should live under crates/")
        .to_path_buf()
}

#[test]
fn schema_exports_generated_contract_artifacts_from_rust() {
    let root = project_root();
    let schema_path = root.join("schemas/command.schema.json");
    let draft_schema_path = root.join("schemas/draft.schema.json");
    let generated_dir = root.join("apps/desktop-electron/src/generated");

    let schema_json = command_schema_json();
    assert_or_update_contract_file(&schema_path, &format!("{schema_json}\n"));

    let draft_schema_json = draft_schema_json();
    assert_or_update_contract_file(&draft_schema_path, &format!("{draft_schema_json}\n"));

    let command_envelope_ts = ts_contract_with_prelude(
        "import type { Draft, MaterialId, MaterialKind } from \"./Draft\";\n\n",
        &[
            export_decl::<CommandName>(),
            export_decl::<PingCommandPayload>(),
            export_decl::<VersionCommandPayload>(),
            export_decl::<ProbeMediaRuntimeCommandPayload>(),
            export_decl::<ImportMaterialCommandPayload>(),
            export_decl::<ListMaterialsCommandPayload>(),
            export_decl::<ListMissingMaterialsCommandPayload>(),
            export_decl::<CommandPayload>(),
            export_decl::<CommandEnvelope>(),
        ],
    );
    assert_or_update_contract_file(
        generated_dir.join("CommandEnvelope.ts"),
        &command_envelope_ts,
    );

    let command_result_ts = ts_contract_with_prelude(
        "import type { Draft, Material, MaterialId, MaterialStatus } from \"./Draft\";\n\n",
        &[
            export_decl::<CommandErrorKind>(),
            export_decl::<CommandError>(),
            export_decl::<CommandEvent>(),
            export_decl::<CommandResultEnvelope<()>>(),
            export_decl::<MissingMaterialCommandDiagnosticKind>(),
            export_decl::<MissingMaterialCommandDiagnostic>(),
            export_decl::<ImportMaterialResponse>(),
            export_decl::<ListMaterialsResponse>(),
            export_decl::<ListMissingMaterialsResponse>(),
        ],
    );
    assert_or_update_contract_file(
        generated_dir.join("CommandResultEnvelope.ts"),
        &command_result_ts,
    );

    let draft_ts = ts_contract(&[
        export_decl::<DraftId>(),
        export_decl::<MaterialId>(),
        export_decl::<TrackId>(),
        export_decl::<SegmentId>(),
        export_decl::<Microseconds>(),
        export_decl::<DraftSchemaVersion>(),
        export_decl::<DraftMetadata>(),
        export_decl::<RationalFrameRate>(),
        export_decl::<MaterialKind>(),
        export_decl::<MaterialStatus>(),
        export_decl::<MaterialMetadata>(),
        export_decl::<Material>(),
        export_decl::<TrackKind>(),
        export_decl::<MainTrackMagnet>(),
        export_decl::<SourceTimerange>(),
        export_decl::<TargetTimerange>(),
        export_decl::<Keyframe>(),
        export_decl::<Filter>(),
        export_decl::<Transition>(),
        export_decl::<Segment>(),
        export_decl::<Track>(),
        export_decl::<Draft>(),
    ]);
    assert_or_update_contract_file(generated_dir.join("Draft.ts"), &draft_ts);
}

fn export_decl<T>() -> String
where
    T: TS + 'static,
{
    format!("export {}\n", T::decl(&Config::new()))
}

fn ts_contract(declarations: &[String]) -> String {
    ts_contract_with_prelude("", declarations)
}

fn ts_contract_with_prelude(prelude: &str, declarations: &[String]) -> String {
    let mut ts = String::from(
        "// This file was generated by Rust ts-rs declarations. Do not edit this file manually.\n\n",
    );
    ts.push_str(prelude);
    for declaration in declarations {
        ts.push_str(declaration);
    }
    ts
}

fn assert_or_update_contract_file(path: impl AsRef<Path>, expected: &str) {
    let path = path.as_ref();

    if env::var_os("VE_UPDATE_GENERATED_CONTRACTS").as_deref() == Some(std::ffi::OsStr::new("1")) {
        fs::create_dir_all(path.parent().expect("contract path should have parent"))
            .expect("contract directory should be created");
        fs::write(path, expected).expect("contract artifact should be written");
        return;
    }

    let actual = fs::read_to_string(path).unwrap_or_else(|error| {
        panic!(
            "committed contract artifact should be readable at {}: {error}",
            path.display()
        )
    });
    assert_eq!(
        actual,
        expected,
        "generated contract artifact is stale: {}. Run with VE_UPDATE_GENERATED_CONTRACTS=1 to refresh.",
        path.display()
    );
}

#[test]
fn schema_fixtures_validate_command_contracts() {
    let root = project_root();
    let fixture_dir = root.join("fixtures/draft");
    let positive = BTreeSet::from(["minimal-command.json"]);
    let negative = BTreeSet::from([
        "invalid-mismatched-command-payload.json",
        "invalid-unknown-field.json",
    ]);

    let fixture_names = fs::read_dir(&fixture_dir)
        .expect("fixtures/draft directory should exist")
        .map(|entry| {
            let entry = entry.expect("fixture directory entry should be readable");
            let path = entry.path();
            assert_eq!(
                path.extension().and_then(|extension| extension.to_str()),
                Some("json"),
                "fixtures/draft should only contain JSON fixtures: {}",
                path.display()
            );
            entry
                .file_name()
                .into_string()
                .expect("fixture names should be UTF-8")
        })
        .collect::<BTreeSet<_>>();

    let expected = positive.union(&negative).copied().collect::<BTreeSet<_>>();
    let actual = fixture_names
        .iter()
        .map(String::as_str)
        .collect::<BTreeSet<_>>();
    assert_eq!(
        actual, expected,
        "every draft JSON fixture must be explicitly classified"
    );

    let schema_json: serde_json::Value = serde_json::from_str(&command_schema_json())
        .expect("generated command schema should parse");
    let schema =
        jsonschema::validator_for(&schema_json).expect("generated command schema should compile");

    for fixture_name in positive {
        let value = read_fixture(&fixture_dir, fixture_name);
        serde_json::from_value::<CommandEnvelope>(value.clone())
            .expect("positive fixture should deserialize through Rust model");
        schema
            .validate(&value)
            .expect("positive fixture should validate against JSON Schema");
    }

    for fixture_name in negative {
        let value = read_fixture(&fixture_dir, fixture_name);
        assert!(
            serde_json::from_value::<CommandEnvelope>(value.clone()).is_err(),
            "negative fixture should fail Rust model deserialization: {fixture_name}"
        );
        assert!(
            schema.validate(&value).is_err(),
            "negative fixture should fail JSON Schema validation: {fixture_name}"
        );
    }
}

fn read_fixture(fixture_dir: &Path, fixture_name: &str) -> serde_json::Value {
    serde_json::from_slice(
        &fs::read(fixture_dir.join(fixture_name)).expect("fixture should be readable"),
    )
    .expect("fixture should parse as JSON")
}

fn command_schema_json() -> String {
    let schema = schema_for!(CommandEnvelope);
    let mut schema_value =
        serde_json::to_value(schema).expect("command schema should serialize to JSON value");
    schema_value
        .as_object_mut()
        .expect("command schema should be a JSON object")
        .insert("oneOf".to_string(), command_payload_pairing_constraints());

    serde_json::to_string_pretty(&schema_value).expect("command schema should serialize")
}

fn draft_schema_json() -> String {
    let schema = schema_for!(Draft);
    serde_json::to_string_pretty(&schema).expect("draft schema should serialize")
}

fn command_payload_pairing_constraints() -> serde_json::Value {
    json!([
        {
            "properties": {
                "command": { "const": "ping" },
                "payload": {
                    "properties": {
                        "kind": { "const": "ping" }
                    },
                    "required": ["kind"]
                }
            }
        },
        {
            "properties": {
                "command": { "const": "version" },
                "payload": {
                    "properties": {
                        "kind": { "const": "version" }
                    },
                    "required": ["kind"]
                }
            }
        },
        {
            "properties": {
                "command": { "const": "probeMediaRuntime" },
                "payload": {
                    "properties": {
                        "kind": { "const": "probeMediaRuntime" }
                    },
                    "required": ["kind"]
                }
            }
        },
        {
            "properties": {
                "command": { "const": "importMaterial" },
                "payload": {
                    "properties": {
                        "kind": { "const": "importMaterial" }
                    },
                    "required": ["kind"]
                }
            }
        },
        {
            "properties": {
                "command": { "const": "listMaterials" },
                "payload": {
                    "properties": {
                        "kind": { "const": "listMaterials" }
                    },
                    "required": ["kind"]
                }
            }
        },
        {
            "properties": {
                "command": { "const": "listMissingMaterials" },
                "payload": {
                    "properties": {
                        "kind": { "const": "listMissingMaterials" }
                    },
                    "required": ["kind"]
                }
            }
        }
    ])
}
