#!/usr/bin/env bash
set -euo pipefail

if ! command -v rg >/dev/null 2>&1; then
  echo "phase4-source-guards: rg is required" >&2
  exit 1
fi

RENDERER_DIR="apps/desktop-electron/src/renderer"
TEST_DIR="apps/desktop-electron/tests"
GENERATED_DIR="apps/desktop-electron/src/generated"
GENERATED_HEADER="This file was generated by Rust ts-rs declarations. Do not edit this file manually."

fail_if_matches() {
  local description="$1"
  local pattern="$2"
  shift 2

  local output
  if output=$(rg -n --pcre2 "$pattern" "$@" 2>/dev/null); then
    echo "phase4-source-guards: ${description}" >&2
    echo "$output" >&2
    exit 1
  fi
}

require_generated_header() {
  local file="$1"

  if ! rg -n --fixed-strings "$GENERATED_HEADER" "$file" >/dev/null; then
    echo "phase4-source-guards: missing generated header in ${file}" >&2
    exit 1
  fi
}

renderer_files=("$RENDERER_DIR")
user_facing_files=("$RENDERER_DIR" "$TEST_DIR")

fail_if_matches \
  "renderer must not mutate Draft.tracks or Track.segments arrays directly" \
  '(?:draft|current|nextDraft|workspace\.draft)\.tracks\s*=|\.tracks\.(?:push|pop|shift|unshift|splice|sort|reverse)\s*\(|(?:track|candidate)\.segments\s*=|\.segments\.(?:push|pop|shift|unshift|splice|sort|reverse)\s*\(' \
  "${renderer_files[@]}"

fail_if_matches \
  "renderer must not assign timeline timeranges or main-track magnet semantics directly" \
  '\.(?:sourceTimerange|targetTimerange|mainTrackMagnet)\s*=|(?:sourceTimerange|targetTimerange|mainTrackMagnet)\.(?:start|duration|enabled)\s*=' \
  "${renderer_files[@]}"

fail_if_matches \
  "renderer must not import or require Electron, Node, or native binding APIs" \
  'from\s+["'\''](?:electron|node:|fs|path|child_process)(?:/|["'\''])|import\s+["'\''](?:electron|node:|fs|path|child_process)(?:/|["'\''])|require\s*\(\s*["'\''](?:electron|node:|fs|path|child_process)(?:/|["'\''])|createRequire|nativeBinding|bindings_node|@video-editor/bindings' \
  "${renderer_files[@]}"

fail_if_matches \
  "renderer must not expose raw IPC or process globals" \
  '\bipcRenderer\b|\bprocess\.' \
  "${renderer_files[@]}"

fail_if_matches \
  "renderer must not construct FFmpeg, render graph, preview cache, or waveform behavior" \
  'ffmpeg|ffprobe|filter_complex|renderGraph|ffmpegScripts|previewCache|waveform' \
  "${renderer_files[@]}"

fail_if_matches \
  "renderer command payload timing must use integer microsecond inputs, not seconds-to-microseconds float conversion" \
  'durationSeconds|\*\s*1_000_000' \
  "${renderer_files[@]}"

fail_if_matches \
  "tests must not patch private Electron IPC internals" \
  '_invokeHandlers' \
  "$TEST_DIR"

english_terms='Video editor smoke workbench|Feature categories|Material bin|Preview monitor|Inspector|Timeline|Materials|Media|Text|Audio|Effects|Asset|Clip|workbench'

fail_if_matches \
  "English workspace labels are forbidden in JSX visible text" \
  ">[[:space:]]*(?:${english_terms})[[:space:]]*<" \
  "${user_facing_files[@]}"

fail_if_matches \
  "English workspace labels are forbidden in ARIA, title, placeholder, and form labels" \
  "(?:aria-label|aria-labelledby|title|placeholder|alt)=\\{?['\"][^'\"]*(?:${english_terms})" \
  "${user_facing_files[@]}"

fail_if_matches \
  "English workspace labels are forbidden in Playwright visible locators" \
  "getByRole\\([^\\n]*name\\s*:\\s*(?:['\"][^'\"]*(?:${english_terms})|/[^/]*(?:${english_terms}))|getBy(?:Text|Label|Placeholder|Title)\\(\\s*(?:['\"][^'\"]*(?:${english_terms})|/[^/]*(?:${english_terms}))" \
  "${user_facing_files[@]}"

fail_if_matches \
  "known English smoke copy must not remain in source or tests" \
  'Video editor smoke workbench|Feature categories|Material bin|Preview monitor|workbench' \
  "${user_facing_files[@]}"

require_generated_header "${GENERATED_DIR}/CommandEnvelope.ts"
require_generated_header "${GENERATED_DIR}/CommandResultEnvelope.ts"
require_generated_header "${GENERATED_DIR}/Draft.ts"

git diff --exit-code schemas "$GENERATED_DIR"
