#!/usr/bin/env bash
set -euo pipefail

fail() {
  echo "phase18 ABI drift violation: $1" >&2
  exit 1
}

CBINDGEN_VERSION="0.29.4"
ROOT_DIR="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
TOOL_ROOT="${PHASE18_CBINDGEN_TOOL_ROOT:-$ROOT_DIR/target/phase18-tools/cbindgen-$CBINDGEN_VERSION}"
INSTALL_ROOT="${PHASE18_CBINDGEN_INSTALL_ROOT:-$TOOL_ROOT/install}"
CARGO_HOME_DIR="${PHASE18_CBINDGEN_CARGO_HOME:-$TOOL_ROOT/cargo-home}"
DEFAULT_CBINDGEN_BIN="$INSTALL_ROOT/bin/cbindgen"
CBINDGEN_CONFIG="crates/bindings_c/cbindgen.toml"
CBINDGEN_HEADER="crates/bindings_c/include/video_editor_runtime.h"

require_file() {
  local file="$1"
  [ -f "$file" ] || fail "missing required ABI artifact ${file}"
}

cbindgen_version_matches() {
  local bin="$1"
  local version_output
  [ -x "$bin" ] || return 1
  version_output="$("$bin" --version 2>/dev/null || true)"
  [ "$version_output" = "cbindgen ${CBINDGEN_VERSION}" ]
}

assert_cbindgen_version() {
  local bin="$1"
  local version_output
  [ -x "$bin" ] || fail "resolved cbindgen binary is not executable: ${bin}"
  version_output="$("$bin" --version 2>/dev/null || true)"
  if [ "$version_output" != "cbindgen ${CBINDGEN_VERSION}" ]; then
    fail "resolved cbindgen version must be exactly cbindgen ${CBINDGEN_VERSION}; got '${version_output:-unavailable}' from ${bin}"
  fi
}

bootstrap_cbindgen() {
  if [ -n "${PHASE18_CBINDGEN_BIN:-}" ]; then
    printf '%s\n' "$PHASE18_CBINDGEN_BIN"
    return 0
  fi

  mkdir -p "$INSTALL_ROOT" "$CARGO_HOME_DIR"
  if [ -x "$DEFAULT_CBINDGEN_BIN" ]; then
    printf '%s\n' "$DEFAULT_CBINDGEN_BIN"
    return 0
  fi

  echo "Installing project-local cbindgen ${CBINDGEN_VERSION} into ${INSTALL_ROOT}" >&2
  CARGO_HOME="$CARGO_HOME_DIR" cargo install cbindgen \
    --version "$CBINDGEN_VERSION" \
    --locked \
    --root "$INSTALL_ROOT"
  printf '%s\n' "$DEFAULT_CBINDGEN_BIN"
}

check_header_drift() {
  local repo_root="$1"
  local header="$2"
  git -C "$repo_root" diff --exit-code -- "$header"
}

run_drift_check() {
  require_file "$CBINDGEN_CONFIG"
  require_file "$CBINDGEN_HEADER"

  local cbindgen_bin
  cbindgen_bin="$(bootstrap_cbindgen)"
  echo "Using cbindgen: ${cbindgen_bin}"
  assert_cbindgen_version "$cbindgen_bin"

  (
    cd "$ROOT_DIR"
    "$cbindgen_bin" \
      --config "$CBINDGEN_CONFIG" \
      --crate bindings_c \
      --output "$CBINDGEN_HEADER"
    check_header_drift "$ROOT_DIR" "$CBINDGEN_HEADER"
  )
}

run_self_test() {
  local tmp_dir good_bin bad_bin header
  tmp_dir="$(mktemp -d)"
  trap 'rm -rf "$tmp_dir"' RETURN
  mkdir -p "$tmp_dir/bin" "$tmp_dir/repo/crates/bindings_c/include"

  good_bin="$tmp_dir/bin/cbindgen-good"
  bad_bin="$tmp_dir/bin/cbindgen-bad"
  printf '%s\n' '#!/usr/bin/env bash' 'if [ "${1:-}" = "--version" ]; then echo "cbindgen 0.29.4"; exit 0; fi' 'exit 0' >"$good_bin"
  printf '%s\n' '#!/usr/bin/env bash' 'if [ "${1:-}" = "--version" ]; then echo "cbindgen 0.29.5"; exit 0; fi' 'exit 0' >"$bad_bin"
  chmod +x "$good_bin" "$bad_bin"

  assert_cbindgen_version "$good_bin"
  if cbindgen_version_matches "$bad_bin"; then
    fail "self-test accepted a non-pinned cbindgen version"
  fi

  git -C "$tmp_dir/repo" init -q
  git -C "$tmp_dir/repo" config user.email "phase18@example.invalid"
  git -C "$tmp_dir/repo" config user.name "Phase 18 Guard"
  header="crates/bindings_c/include/video_editor_runtime.h"
  printf '%s\n' "/* generated by cbindgen ${CBINDGEN_VERSION} */" >"$tmp_dir/repo/$header"
  git -C "$tmp_dir/repo" add "$header"
  git -C "$tmp_dir/repo" commit -qm "baseline header"
  printf '%s\n' "/* manual drift */" >>"$tmp_dir/repo/$header"
  if check_header_drift "$tmp_dir/repo" "$header" >/dev/null 2>&1; then
    fail "self-test did not reject manual C header drift"
  fi

  echo "phase18 ABI drift self-test passed"
  rm -rf "$tmp_dir"
  trap - RETURN
}

if [ "${1:-}" = "--" ]; then
  shift
fi

case "${1:-}" in
  --self-test)
    run_self_test
    ;;
  -h|--help)
    echo "Usage: bash scripts/phase18-abi-drift.sh [--self-test]"
    ;;
  *)
    run_drift_check
    ;;
esac
