#!/usr/bin/env bash
set -euo pipefail

fail_matches() {
  local message="$1"
  local pattern="$2"
  shift 2
  local matches
  matches="$(
    rg -n "$pattern" "$@" 2>/dev/null \
      | rg -v ':[[:space:]]*(//|/\*|\*|#)' \
      | rg -v "renderGraphFailed" \
      | rg -v "renderGraphGpu" \
      || true
  )"
  if [ -n "$matches" ]; then
    printf '%s\n' "$matches" >&2
    echo "$message" >&2
    exit 1
  fi
}

fail_matches \
  "renderer must not own FFmpeg, render graph, export script, process, validation, or cache semantics" \
  "ffmpeg|ffprobe|filter_complex|filterComplex|FfmpegJob|renderGraph|RenderGraph|cacheKey|cache key|previewCache|preview cache|ffmpegArgs|ffmpegScripts|exportScript|processHandle|validationExpectation|OutputValidation|child_process|spawn\\(|execFile|exec\\(|process\\." \
  apps/desktop-electron/src/renderer \
  --glob '!commandHelpers.ts'

fail_matches \
  "renderer must not own preview invalidation overlap or cache fingerprint semantics" \
  "changedRanges|changedMaterialIds|materialDependencies|semanticFingerprint|previewCacheKey|previewInvalidation|invalidatePreviewCache" \
  apps/desktop-electron/src/renderer \
  --glob '!commandHelpers.ts'

fail_matches \
  "draft persistence must not contain derived render, preview, proxy, waveform, thumbnail, export, validation, or cache artifacts" \
  "\\b(thumbnails|thumbnailPath|waveforms|waveformPath|previewCaches|previewCache|renderGraph|ffmpegScripts|ffmpegArgs|filterComplex|exportScript|exports|proxyFiles|proxyPath|outputValidation|validationExpectation)\\b" \
  schemas/draft.schema.json fixtures/draft/positive

fail_matches \
  "generic preview command envelope API must not be public; use project-session preview or realtime scheduler APIs" \
  "requestPreviewDecode|releasePreviewFrame|requestPreviewFrame|requestPreviewSegment|invalidatePreviewCache|PreviewDecodeRequest|ReleasePreviewFrameCommandPayload|RequestPreviewFrameCommandPayload|RequestPreviewSegmentCommandPayload|InvalidatePreviewCacheCommandPayload" \
  apps/desktop-electron/src/generated/CommandEnvelope.ts \
  schemas/command.schema.json

rg -n "PreviewArtifactResponse" \
  apps/desktop-electron/src/generated/CommandResultEnvelope.ts >/dev/null

rg -n "startExport|getExportJobStatus|cancelExport" \
  apps/desktop-electron/src/generated/CommandEnvelope.ts >/dev/null

rg -n "ExportJobStatusResponse|ExportValidationReport|ExportDiagnostic" \
  apps/desktop-electron/src/generated/CommandResultEnvelope.ts >/dev/null

head -n 1 apps/desktop-electron/src/generated/CommandEnvelope.ts \
  | rg "generated by Rust ts-rs declarations" >/dev/null
head -n 1 apps/desktop-electron/src/generated/CommandResultEnvelope.ts \
  | rg "generated by Rust ts-rs declarations" >/dev/null

FLOAT_TIME_MATCHES="$(
  rg -n "durationSeconds|duration_seconds|seconds: f32|seconds: f64|\\bf32\\b|\\bf64\\b" \
    crates/draft_model/src schemas/command.schema.json apps/desktop-electron/src/generated \
    | rg -v '^crates/draft_model/src/canvas.rs:' \
    || true
)"
if [ -n "$FLOAT_TIME_MATCHES" ]; then
    printf '%s\n' "$FLOAT_TIME_MATCHES" >&2
    echo "preview/export command contracts must use integer microseconds, not naked floating time" >&2
    exit 1
fi
