#!/usr/bin/env bash
set -euo pipefail

rg -n "ffmpeg|ffprobe|filter_complex|renderGraph|cacheKey|cache key|child_process|spawn\\(" \
  apps/desktop-electron/src/renderer && {
    echo "renderer must not own FFmpeg, render graph, cache key, or process semantics" >&2
    exit 1
  } || true

rg -n "invalidatePreviewCache|changedRanges|changedMaterialIds|materialDependencies|semanticFingerprint|execFile|exec\\(|process\\." \
  apps/desktop-electron/src/renderer --glob '!commandHelpers.ts' && {
    echo "renderer must not own preview invalidation overlap, cache fingerprint, or process execution semantics" >&2
    exit 1
  } || true

rg -n "ffmpegArgs|filterComplex|ffmpegScripts|renderGraph|previewCache" \
  schemas/draft.schema.json fixtures/draft/positive && {
    echo "draft persistence must not contain derived render or preview cache artifacts" >&2
    exit 1
  } || true

rg -n "requestPreviewFrame|requestPreviewSegment|invalidatePreviewCache" \
  apps/desktop-electron/src/generated/CommandEnvelope.ts >/dev/null

rg -n "PreviewArtifactResponse|PreviewCacheInvalidationResponse" \
  apps/desktop-electron/src/generated/CommandResultEnvelope.ts >/dev/null

head -n 1 apps/desktop-electron/src/generated/CommandEnvelope.ts \
  | rg "generated by Rust ts-rs declarations" >/dev/null
head -n 1 apps/desktop-electron/src/generated/CommandResultEnvelope.ts \
  | rg "generated by Rust ts-rs declarations" >/dev/null

rg -n "durationSeconds|duration_seconds|seconds: f32|seconds: f64|\\bf32\\b|\\bf64\\b" \
  crates/draft_model/src schemas/command.schema.json apps/desktop-electron/src/generated && {
    echo "preview/export command contracts must use integer microseconds, not naked floating time" >&2
    exit 1
  } || true
