use std::fs;
use std::path::Path;

use artifact_store::blob_store::{BlobStore, BlobWriteIntent};
use artifact_store::dependencies::{
    ArtifactDependency, DependencyUpsert, upsert_artifact_dependencies,
};
use artifact_store::gc::{
    GcMode, TombstoneReason, collect_garbage, plan_garbage_collection, sweep_temporary_blobs,
};
use artifact_store::jobs::{
    ArtifactGenerationRequest, ArtifactKind, GenerationProgress, create_generation_job,
    start_generation_chunk,
};
use artifact_store::manifest::{
    ManifestGenerationOptions, generate_sync_manifest, manifest_fingerprint,
    write_sync_manifest_artifact,
};
use artifact_store::paths::{blob_tmp_path, derived_root_path};
use artifact_store::quota::{QuotaPolicy, QuotaSeverity, compute_quota_state, set_quota_policy};
use artifact_store::schema::open_artifact_store;
use rusqlite::params;
use serde_json::json;

#[test]
fn gc_quota_manifest_gc_dry_run_preserves_live_artifacts_jobs_and_source_media() {
    let sandbox = tempfile::tempdir().expect("tempdir should be created");
    let bundle_path = sandbox.path().join("draft.veproj");
    fs::create_dir_all(&bundle_path).expect("bundle should be created");
    fs::write(bundle_path.join("project.json"), "{}").expect("project json should be written");
    fs::create_dir_all(bundle_path.join("media")).expect("media dir should be created");
    fs::write(bundle_path.join("media/source.mp4"), b"source media")
        .expect("source media should be written");

    let ready = write_artifact(&bundle_path, "artifact-ready", "thumbnail", b"ready bytes");
    let dirty_live = write_artifact(
        &bundle_path,
        "artifact-dirty-live",
        "waveform",
        b"dirty-but-live bytes",
    );
    let job_live = write_artifact(
        &bundle_path,
        "artifact-job-live",
        "proxy",
        b"active job bytes",
    );
    let stale = write_artifact(&bundle_path, "artifact-stale", "proxy", b"stale bytes");

    let mut store = open_artifact_store(&bundle_path).expect("store should open");
    store
        .connection()
        .execute(
            "UPDATE artifact SET dirty = 1, status = 'running' WHERE artifact_id = ?1",
            ["artifact-dirty-live"],
        )
        .expect("dirty row should update");
    upsert_artifact_dependencies(
        &mut store,
        "artifact-dirty-live",
        vec![DependencyUpsert::new(ArtifactDependency::material(
            "material-001",
        ))],
    )
    .expect("dirty live dependency should persist");
    create_generation_job(
        &mut store,
        ArtifactGenerationRequest {
            job_id: "job-active".to_owned(),
            artifact_id: Some("artifact-job-live".to_owned()),
            kind: ArtifactKind::Proxy,
            stable_key: "material:source:job-live".to_owned(),
            resource_id: None,
            material_id: None,
            source_ref: None,
            generation_parameters_json: json!({ "kind": "proxy" }),
            source_fingerprint: Some("source:v1".to_owned()),
            runtime_capability_fingerprint: Some("runtime:v1".to_owned()),
            output_profile_fingerprint: Some("output:v1".to_owned()),
            graph_fingerprint: Some("graph:v1".to_owned()),
            chunks: vec![GenerationProgress::new(Some(0), Some(1_000_000), Some(0))],
        },
    )
    .expect("active job should persist");
    start_generation_chunk(&mut store, "job-active", 0).expect("chunk should be active");
    store
        .connection()
        .execute(
            "UPDATE artifact
             SET status = 'dirty', dirty = 1, updated_at_unix_ms = updated_at_unix_ms + 1
             WHERE artifact_id = ?1",
            ["artifact-stale"],
        )
        .expect("stale artifact should be marked dirty");

    let plan = plan_garbage_collection(&store).expect("gc plan should be built");

    assert_candidate_ids(&plan.candidates, &["artifact-stale"]);
    assert!(path_exists(&bundle_path, &ready));
    assert!(path_exists(&bundle_path, &dirty_live));
    assert!(path_exists(&bundle_path, &job_live));
    assert!(bundle_path.join("project.json").exists());
    assert!(bundle_path.join("media/source.mp4").exists());

    let outcome =
        collect_garbage(&mut store, GcMode::DryRun).expect("dry run should not delete files");
    assert_eq!(outcome.deleted_blob_count, 0);
    assert_eq!(outcome.reclaimable_bytes, stale.byte_count);
    assert!(path_exists(&bundle_path, &stale));
    assert_eq!(artifact_status(&store, "artifact-stale"), "dirty");
}

#[test]
fn gc_quota_manifest_gc_includes_dirty_generated_artifacts_with_dependencies() {
    let sandbox = tempfile::tempdir().expect("tempdir should be created");
    let bundle_path = sandbox.path().join("draft.veproj");
    let stale = write_artifact(
        &bundle_path,
        "artifact-dirty-generated",
        "proxy",
        b"stale generated bytes",
    );
    let mut store = open_artifact_store(&bundle_path).expect("store should open");
    upsert_artifact_dependencies(
        &mut store,
        "artifact-dirty-generated",
        vec![
            DependencyUpsert::new(ArtifactDependency::material("material-001")),
            DependencyUpsert::new(ArtifactDependency::resource("material:material-001")),
            DependencyUpsert::new(ArtifactDependency::generation_parameters(json!({
                "kind": "proxy"
            }))),
        ],
    )
    .expect("generated artifact dependencies should persist");
    store
        .connection()
        .execute(
            "UPDATE artifact SET dirty = 1, status = 'dirty' WHERE artifact_id = ?1",
            ["artifact-dirty-generated"],
        )
        .expect("generated artifact should be dirty");

    let plan = plan_garbage_collection(&store).expect("gc plan should be built");

    assert_candidate_ids(&plan.candidates, &["artifact-dirty-generated"]);
    assert_eq!(plan.reclaimable_bytes, stale.byte_count);
}

#[test]
fn gc_quota_manifest_gc_apply_tombstones_and_deletes_only_contained_candidates() {
    let sandbox = tempfile::tempdir().expect("tempdir should be created");
    let bundle_path = sandbox.path().join("draft.veproj");
    let stale = write_artifact(&bundle_path, "artifact-stale-apply", "proxy", b"delete me");
    let mut store = open_artifact_store(&bundle_path).expect("store should open");
    store
        .connection()
        .execute(
            "UPDATE artifact SET dirty = 1, status = 'dirty' WHERE artifact_id = ?1",
            ["artifact-stale-apply"],
        )
        .expect("stale artifact should be dirty");
    insert_artifact_row(
        &store,
        "artifact-absolute-path",
        "/tmp/should-not-delete.bin",
        "blake3:v1:absolute",
        3,
        "dirty",
    );
    insert_artifact_row(
        &store,
        "artifact-traversal-path",
        "../escape.bin",
        "blake3:v1:traversal",
        4,
        "dirty",
    );
    #[cfg(unix)]
    {
        let outside = sandbox.path().join("outside");
        fs::create_dir_all(&outside).expect("outside dir should be created");
        std::os::unix::fs::symlink(
            &outside,
            derived_root_path(&bundle_path).join("escape-link"),
        )
        .expect("escape symlink should be created");
        insert_artifact_row(
            &store,
            "artifact-symlink-path",
            "escape-link/owned.bin",
            "blake3:v1:symlink",
            5,
            "dirty",
        );
    }

    let outcome = collect_garbage(&mut store, GcMode::Apply).expect("apply gc should succeed");

    assert_eq!(outcome.deleted_artifact_ids, vec!["artifact-stale-apply"]);
    assert_eq!(outcome.deleted_blob_count, 1);
    assert_eq!(outcome.released_bytes, stale.byte_count);
    assert!(!path_exists(&bundle_path, &stale));
    assert_eq!(
        artifact_status(&store, "artifact-stale-apply"),
        "tombstoned"
    );

    let tombstone = tombstone_for(&store, "artifact-stale-apply");
    assert_eq!(tombstone.0, stale.blob_relative_path);
    assert_eq!(tombstone.1, stale.blob_fingerprint.to_string());
    assert_eq!(tombstone.2, stale.byte_count);
    assert_eq!(tombstone.3, TombstoneReason::GarbageCollected.as_str());
    assert_eq!(
        artifact_status(&store, "artifact-absolute-path"),
        "dirty",
        "absolute path rows must fail closed"
    );
    assert_eq!(
        artifact_status(&store, "artifact-traversal-path"),
        "dirty",
        "traversal rows must fail closed"
    );
    #[cfg(unix)]
    assert_eq!(
        artifact_status(&store, "artifact-symlink-path"),
        "dirty",
        "symlink escape rows must fail closed"
    );
}

#[test]
fn gc_quota_manifest_temp_blob_sweep_removes_abandoned_temp_files_only() {
    let sandbox = tempfile::tempdir().expect("tempdir should be created");
    let bundle_path = sandbox.path().join("draft.veproj");
    let ready = write_artifact(&bundle_path, "artifact-ready-temp", "thumbnail", b"ready");
    let temp_dir = blob_tmp_path(&bundle_path);
    fs::create_dir_all(&temp_dir).expect("temp dir should be created");
    fs::write(temp_dir.join("abandoned.tmp"), b"partial").expect("temp file should be written");

    let removed = sweep_temporary_blobs(&bundle_path).expect("temp sweep should succeed");

    assert_eq!(removed.removed_temp_files, 1);
    assert!(!temp_dir.join("abandoned.tmp").exists());
    assert!(path_exists(&bundle_path, &ready));
}

#[test]
fn gc_quota_manifest_quota_counts_artifact_rows_and_gc_candidates_not_path_scans() {
    let sandbox = tempfile::tempdir().expect("tempdir should be created");
    let bundle_path = sandbox.path().join("draft.veproj");
    let ready = write_artifact(&bundle_path, "artifact-quota-ready", "thumbnail", b"ready");
    let stale = write_artifact(
        &bundle_path,
        "artifact-quota-stale",
        "proxy",
        b"stale bytes",
    );
    fs::write(
        sandbox.path().join("external-source.mp4"),
        vec![1_u8; 10 * 1024],
    )
    .expect("external source should be written");
    fs::write(
        derived_root_path(&bundle_path).join("blobs/untracked.bin"),
        vec![2_u8; 8 * 1024],
    )
    .expect("untracked derived file should be written");

    let store = open_artifact_store(&bundle_path).expect("store should open");
    store
        .connection()
        .execute(
            "UPDATE artifact SET dirty = 1, status = 'dirty' WHERE artifact_id = ?1",
            ["artifact-quota-stale"],
        )
        .expect("stale artifact should be dirty");

    let state = compute_quota_state(&store).expect("quota state should compute");

    assert_eq!(
        state.snapshot.used_bytes,
        ready.byte_count + stale.byte_count
    );
    assert_eq!(state.snapshot.reclaimable_bytes, stale.byte_count);
    assert_eq!(state.snapshot.source_media_bytes, 0);
    assert_eq!(state.snapshot.untracked_blob_bytes, 0);
    assert_eq!(
        state.labels.reclaimable_label,
        format_bytes(stale.byte_count)
    );
}

#[test]
fn gc_quota_manifest_quota_warning_and_labels_are_rust_owned_and_ui_safe() {
    let sandbox = tempfile::tempdir().expect("tempdir should be created");
    let bundle_path = sandbox.path().join("draft.veproj");
    let ready = write_artifact(
        &bundle_path,
        "artifact-quota-warning",
        "thumbnail",
        b"warning",
    );
    let mut store = open_artifact_store(&bundle_path).expect("store should open");
    set_quota_policy(
        &mut store,
        QuotaPolicy {
            byte_limit: Some(ready.byte_count),
            warning_ratio_per_mille: 750,
        },
    )
    .expect("quota policy should persist");

    let state = compute_quota_state(&store).expect("quota state should compute");

    assert_eq!(state.severity, QuotaSeverity::Warning);
    assert!(state.cleanup_available);
    assert_eq!(state.status_label, "缓存空间偏高");
    assert_eq!(state.labels.used_label, format_bytes(ready.byte_count));
    assert_eq!(state.labels.released_label, "0 B");
    let serialized = serde_json::to_string(&state).expect("quota state should serialize");
    for forbidden in [
        "artifact-store.sqlite",
        ".sqlite",
        ".veproj/derived",
        "blake3:v1:",
        "graphNode",
        "dirtyRange",
        "/",
        "C:\\",
    ] {
        assert!(
            !serialized.contains(forbidden),
            "quota state leaked forbidden internal string {forbidden}: {serialized}"
        );
    }
}

#[test]
fn gc_quota_manifest_quota_reports_cleanup_completion_from_tombstones() {
    let sandbox = tempfile::tempdir().expect("tempdir should be created");
    let bundle_path = sandbox.path().join("draft.veproj");
    let stale = write_artifact(
        &bundle_path,
        "artifact-quota-cleaned",
        "waveform",
        b"cleanup bytes",
    );
    let mut store = open_artifact_store(&bundle_path).expect("store should open");
    store
        .connection()
        .execute(
            "UPDATE artifact SET dirty = 1, status = 'dirty' WHERE artifact_id = ?1",
            ["artifact-quota-cleaned"],
        )
        .expect("stale artifact should be dirty");
    collect_garbage(&mut store, GcMode::Apply).expect("cleanup should tombstone stale artifact");

    let state = compute_quota_state(&store).expect("quota state should compute after cleanup");

    assert_eq!(state.severity, QuotaSeverity::Normal);
    assert!(!state.cleanup_available);
    assert_eq!(state.status_label, "缓存清理完成");
    assert_eq!(state.snapshot.released_bytes, stale.byte_count);
    assert_eq!(state.labels.released_label, format_bytes(stale.byte_count));
}

#[test]
fn gc_quota_manifest_sync_manifest_is_deterministic_and_fingerprinted() {
    let first = manifest_json_and_fingerprint();
    let second = manifest_json_and_fingerprint();

    assert_eq!(first.0, second.0, "manifest JSON must be byte-identical");
    assert_eq!(first.1, second.1, "manifest fingerprint must be stable");
    assert!(
        first.1.starts_with("blake3:v1:"),
        "manifest fingerprint must include algorithm prefix"
    );
}

#[test]
fn gc_quota_manifest_sync_manifest_entries_are_project_relative_and_complete() {
    let sandbox = tempfile::tempdir().expect("tempdir should be created");
    let bundle_path = sandbox.path().join("draft.veproj");
    let live = write_artifact(
        &bundle_path,
        "artifact-manifest-live",
        "thumbnail",
        b"manifest live bytes",
    );
    let stale = write_artifact(
        &bundle_path,
        "artifact-manifest-stale",
        "proxy",
        b"manifest stale bytes",
    );
    let mut store = open_artifact_store(&bundle_path).expect("store should open");
    upsert_artifact_dependencies(
        &mut store,
        "artifact-manifest-live",
        vec![
            DependencyUpsert::new(ArtifactDependency::material("material-001")),
            DependencyUpsert::new(ArtifactDependency::graph_node("segment:video:001")),
        ],
    )
    .expect("manifest dependencies should persist");
    store
        .connection()
        .execute(
            "UPDATE artifact SET dirty = 1, status = 'dirty' WHERE artifact_id = ?1",
            ["artifact-manifest-stale"],
        )
        .expect("stale artifact should be dirty");
    collect_garbage(&mut store, GcMode::Apply).expect("stale artifact should tombstone");

    let manifest = generate_sync_manifest(&store, ManifestGenerationOptions::default())
        .expect("manifest should generate");

    assert_eq!(manifest.schema_version, 1);
    assert_eq!(
        manifest.generator_version,
        "artifact-store-sync-manifest-v1"
    );
    assert_eq!(manifest.entries.len(), 1);
    let entry = &manifest.entries[0];
    assert_eq!(entry.artifact_id, "artifact-manifest-live");
    assert_eq!(entry.artifact_kind, "thumbnail");
    assert_eq!(entry.status, "ready");
    assert_eq!(entry.blob_relative_path, live.blob_relative_path);
    assert_eq!(entry.byte_count, live.byte_count);
    assert_eq!(entry.blob_fingerprint, live.blob_fingerprint.to_string());
    assert_eq!(entry.source_fingerprint.as_deref(), Some("source:v1"));
    assert_eq!(entry.graph_fingerprint.as_deref(), Some("graph:v1"));
    assert_eq!(entry.dependencies.len(), 2);
    assert!(entry.blob_relative_path.starts_with("blobs/"));
    assert!(!entry.blob_relative_path.starts_with('/'));
    assert!(!entry.blob_relative_path.contains(".veproj/derived"));
    assert_eq!(manifest.tombstones.len(), 1);
    assert_eq!(
        manifest.tombstones[0].artifact_id,
        "artifact-manifest-stale"
    );
    assert_eq!(
        manifest.tombstones[0].blob_relative_path,
        stale.blob_relative_path
    );
}

#[test]
fn gc_quota_manifest_sync_manifest_has_no_remote_transport_or_credentials() {
    let sandbox = tempfile::tempdir().expect("tempdir should be created");
    let bundle_path = sandbox.path().join("draft.veproj");
    write_artifact(
        &bundle_path,
        "artifact-manifest-local",
        "waveform",
        b"manifest local bytes",
    );
    let store = open_artifact_store(&bundle_path).expect("store should open");

    let manifest = generate_sync_manifest(&store, ManifestGenerationOptions::default())
        .expect("manifest should generate");
    let written = write_sync_manifest_artifact(&bundle_path, &manifest)
        .expect("manifest artifact should write through BlobStore");
    let serialized = serde_json::to_string(&manifest).expect("manifest should serialize");

    assert!(written.blob_relative_path.starts_with("blobs/"));
    for forbidden in [
        "http://",
        "https://",
        "s3://",
        "gs://",
        "token",
        "secret",
        "credential",
        "upload",
        "download",
        "provider",
        "serverRendering",
    ] {
        assert!(
            !serialized.contains(forbidden),
            "manifest introduced remote/cloud transport field {forbidden}: {serialized}"
        );
    }
}

fn write_artifact(
    bundle_path: &Path,
    artifact_id: &str,
    artifact_kind: &str,
    bytes: &[u8],
) -> artifact_store::blob_store::BlobRecord {
    let mut blobs = BlobStore::open(bundle_path).expect("blob store should open");
    blobs
        .write_blob_atomic(
            BlobWriteIntent {
                artifact_id: artifact_id.to_owned(),
                artifact_kind: artifact_kind.to_owned(),
                stable_key: format!("material:source:{artifact_id}"),
                schema_fingerprint: "schema:v1".to_owned(),
                generator_fingerprint: "generator:v1".to_owned(),
                runtime_capability_fingerprint: Some("runtime:v1".to_owned()),
                source_fingerprint: Some("source:v1".to_owned()),
                graph_fingerprint: Some("graph:v1".to_owned()),
                output_profile_fingerprint: Some("output:v1".to_owned()),
                generation_parameters_json: json!({ "artifactId": artifact_id }),
                expected_fingerprint: None,
            },
            bytes,
        )
        .expect("blob should write")
}

fn path_exists(bundle_path: &Path, record: &artifact_store::blob_store::BlobRecord) -> bool {
    derived_root_path(bundle_path)
        .join(&record.blob_relative_path)
        .exists()
}

fn assert_candidate_ids(candidates: &[artifact_store::gc::GcCandidate], expected: &[&str]) {
    let actual = candidates
        .iter()
        .map(|candidate| candidate.artifact_id.as_str())
        .collect::<Vec<_>>();
    assert_eq!(actual, expected);
}

fn insert_artifact_row(
    store: &artifact_store::schema::ArtifactStore,
    artifact_id: &str,
    blob_relative_path: &str,
    blob_fingerprint: &str,
    byte_count: u64,
    status: &str,
) {
    store
        .connection()
        .execute(
            "INSERT INTO artifact (
                artifact_id, artifact_kind, stable_key, blob_relative_path, blob_fingerprint,
                schema_fingerprint, generator_fingerprint, generation_parameters_json, status,
                dirty, byte_count, created_at_unix_ms, updated_at_unix_ms
            ) VALUES (?1, 'proxy', ?2, ?3, ?4, 'schema:v1', 'generator:v1', '{}', ?5, 1, ?6, 0, 0)",
            params![
                artifact_id,
                format!("material:source:{artifact_id}"),
                blob_relative_path,
                blob_fingerprint,
                status,
                byte_count as i64,
            ],
        )
        .expect("artifact row should insert");
}

fn artifact_status(store: &artifact_store::schema::ArtifactStore, artifact_id: &str) -> String {
    store
        .connection()
        .query_row(
            "SELECT status FROM artifact WHERE artifact_id = ?1",
            [artifact_id],
            |row| row.get(0),
        )
        .expect("artifact status should read")
}

fn tombstone_for(
    store: &artifact_store::schema::ArtifactStore,
    artifact_id: &str,
) -> (String, String, u64, String) {
    let (path, fingerprint, bytes, reason): (String, String, i64, String) = store
        .connection()
        .query_row(
            "SELECT blob_relative_path, blob_fingerprint, byte_count, reason
             FROM artifact_tombstone WHERE artifact_id = ?1",
            [artifact_id],
            |row| Ok((row.get(0)?, row.get(1)?, row.get(2)?, row.get(3)?)),
        )
        .expect("tombstone should exist");
    (path, fingerprint, bytes as u64, reason)
}

fn format_bytes(bytes: u64) -> String {
    if bytes < 1024 {
        format!("{bytes} B")
    } else {
        format!("{:.1} KB", bytes as f64 / 1024.0)
    }
}

fn manifest_json_and_fingerprint() -> (String, String) {
    let sandbox = tempfile::tempdir().expect("tempdir should be created");
    let bundle_path = sandbox.path().join("draft.veproj");
    write_artifact(
        &bundle_path,
        "artifact-manifest-a",
        "thumbnail",
        b"manifest a bytes",
    );
    write_artifact(
        &bundle_path,
        "artifact-manifest-b",
        "waveform",
        b"manifest b bytes",
    );
    let mut store = open_artifact_store(&bundle_path).expect("store should open");
    upsert_artifact_dependencies(
        &mut store,
        "artifact-manifest-b",
        vec![DependencyUpsert::new(ArtifactDependency::material(
            "material-001",
        ))],
    )
    .expect("dependency should persist");
    let manifest = generate_sync_manifest(&store, ManifestGenerationOptions::default())
        .expect("manifest should generate");
    (
        serde_json::to_string(&manifest).expect("manifest should serialize"),
        manifest_fingerprint(&manifest).expect("manifest should fingerprint"),
    )
}
